- name: Setup Nginx for Ubuntu
  hosts: webservers
  become: yes
  vars:
    src: webapp/
    dest: /usr/share/nginx/html
  tasks:
    - name: Install Nginx on Fedora
      dnf:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_distribution == "Fedora"
    - name: Clear nginx folder
      ansible.builtin.file:
        state: absent
        path: /usr/share/nginx/html/
      when: ansible_distribution == "Fedora"
    - name: Open the firewall for Nginx (Fedora)
      ansible.builtin.shell: |
        firewall-cmd --permanent --add-service=http
        firewall-cmd --permanent --add-service=https
        firewall-cmd --reload
        exit 0
      when: ansible_distribution == "Fedora"
    - name: Copy project
      copy:
        src: "{{src}}"
        dest: "{{dest}}"
      when: ansible_distribution == "Fedora"
    - name: start nginx
      service:
        name: nginx
        state: started
      when: ansible_distribution == "Fedora"
    - name: Print OS
      debug:
        var: ansible_distribution
      when: ansible_distribution == "Fedora"