- name: Setup Nginx for Ubuntu
  hosts: webservers
  become: yes
  vars:
    src: webapp/
    dest: /var/www/html
  tasks:
    - name: Install packages
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - wget
        - curl
        - zip
        - unzip
      when: ansible_distribution == "Ubuntu"

    - name: Install Nginx on Ubuntu
      apt:
        name: nginx
        state: latest
        update_cache: yes
      register: serverout
      when: ansible_distribution == "Ubuntu"

    - name: Print Output
      debug:
        var: serverout
      when: ansible_distribution == "Ubuntu"

    - name: Copy project
      copy:
        src: "{{src}}"
        dest: "{{dest}}"
      when: ansible_distribution == "Ubuntu"

    - name: Print OS
      debug:
        var: ansible_distribution
      when: ansible_distribution == "Ubuntu"