- name: Setup Web Server
  hosts: webservers
  become: yes
  vars:
    src: webapp/
    dest: /var/www/html
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Copy project
      copy:
        src: "{{src}}"
        dest: "{{dest}}"
    - name: Print OS
      debug:
        var: ansible_distribution